version: "3.7"

networks:
  materialize-feed:

volumes:
  postgresql: {}
  pgadmin: {}
  redis: {}

services:
  postgres:
    image: postgres:11-alpine
    container_name: materialize-feed-postgres
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_DATABASE:-materialize-feed_local}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - materialize-feed

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: materialize-feed-pgadmin
    ports:
      - 5433:80
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USER:-root}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - materialize-feed
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    container_name: materialize-feed-redis
    env_file:
      - .env
    ports:
      - ${CACHE_PORT:-6379}:6379
    command: redis-server
    volumes:
      - redis:/data
    networks:
      - materialize-feed
